### PR TITLE
Update matroska schema to v4

### LINKED ISSUE #3: Filter unknown elements
Some times the recorder can create unknown entries . . . just need to change

```
decoder
    .decode(bufSlices)
    .forEach((elm) => reader.read(elm));
```

to

```
decoder
    .decode(bufSlices)
    .filter((el) => el.type !== 'unknown')
    .forEach((elm) => reader.read(elm));
```

### PR DESCRIPTION
**Pull request by kmathmann**
Fixes #3 by updating the matroska schema to v4 based on [node-matroska](https://github.com/oeuillot/node-matroska/blob/master/lib/schema.js).

*Additional Changes:*
* Removes the 'dist' directory from git. It was outdated and is not required to be versioned by git.
* Removes `tsconfig.json` from the files list so it does not get published to npm (not required in the published package).
* Updates `package-lock.json` to v2 and changes the included urls from the current private registry to the official npm registry.

### CODE REVIEW

**Review by StaZhu — APPROVED** [review]

**Comment by StaZhu** [comment]
Thanks！

**Comment by kmathmann** [comment]
We need to reopen the PR, i did some further testing today and ran into this error oeuillot/node-matroska#10.

**Comment by StaZhu** [comment]
> We need to reopen the PR, i did some further testing today and ran into this error [oeuillot/node-matroska#10](https://github.com/oeuillot/node-matroska/issues/10).

Did you figure out any solution on that?

**Comment by kmathmann** [comment]
I tried [this ](https://github.com/oeuillot/node-matroska/issues/10#issuecomment-1092230643)suggested solution but it didn't worked.
> after i change ColourSpace to UncompressedFourCC and TimecodeScale to TimestampScale it seems fine, at least for the video i am testing with

**Pull request merged**
